# Setup
title:               Daehyeon Choi
tagline:             'Master. Student @ KAIST, C.S'
description:         'I am Daehyeon Choi, and I am Master Student in KAIST I am intersted in Generative Model and its various applications.'
url:                 http://choidaedae.github.io/
baseurl:             
paginate:            5
permalink:           pretty
include:
  - _assets

# About/contact
author:
  name:              Daehyeon Choi
  linkedin:          https://www.linkedin.com/in/daehyeon-choi-570b0a214/
  email:             daehyeonchoi@kaist.ac.kr

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
